{
  "openapi": "3.0.0",
  "info": {
    "title": "FLOCX Marketplace API",
    "version": "1.0.0",
    "description": "This document specifies the API used by the [FLOCX][] Marketplace service.\n\n[flocx]: https://cci-moc.github.io/flocx/"
  },
  "servers": [
    {
      "url": "http://marketplace.example.com/{version}",
      "description": "example endpoint",
      "variables": {
        "version": {
          "enum": [
            "v1"
          ],
          "default": "v1"
        }
      }
    }
  ],
  "security": [
    {
      "KeystoneAuth": []
    }
  ],
  "paths": {
    "/provider": {
      "get": {
        "operationId": "listProviders",
        "summary": "List all registered providers.",
        "responses": {
          "200": {
            "description": "List of all registered providers.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "required": [
                      "id",
                      "endpoint_url"
                    ],
                    "properties": {
                      "endpoint_url": {
                        "type": "string"
                      },
                      "id": {
                        "type": "string"
                      },
                      "created_at": {
                        "type": "string",
                        "format": "date-time"
                      },
                      "updated_at": {
                        "type": "string",
                        "format": "date-time"
                      }
                    },
                    "example": {
                      "id": "f5826b8e-f2aa-4222-9d95-7ed9d05d3f28",
                      "endpoint_url": "http://provider0.example.com",
                      "created_at": "20190529T00:00:00Z",
                      "updated_at": "20190529T00:00:00Z"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "operationId": "createProvider",
        "summary": "Register a new provider with the Marketplace.",
        "requestBody": {
          "description": "Provider to add to the system.",
          "content": {
            "application/json": {
              "schema": {
                "required": [
                  "id",
                  "endpoint_url"
                ],
                "properties": {
                  "endpoint_url": {
                    "type": "string"
                  },
                  "id": {
                    "type": "string"
                  },
                  "created_at": {
                    "type": "string",
                    "format": "date-time"
                  },
                  "updated_at": {
                    "type": "string",
                    "format": "date-time"
                  }
                },
                "example": {
                  "id": "f5826b8e-f2aa-4222-9d95-7ed9d05d3f28",
                  "endpoint_url": "http://provider0.example.com",
                  "created_at": "20190529T00:00:00Z",
                  "updated_at": "20190529T00:00:00Z"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Provider created successfully.",
            "content": {
              "application/json": {
                "schema": {
                  "required": [
                    "id",
                    "endpoint_url"
                  ],
                  "properties": {
                    "endpoint_url": {
                      "type": "string"
                    },
                    "id": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string",
                      "format": "date-time"
                    },
                    "updated_at": {
                      "type": "string",
                      "format": "date-time"
                    }
                  },
                  "example": {
                    "id": "f5826b8e-f2aa-4222-9d95-7ed9d05d3f28",
                    "endpoint_url": "http://provider0.example.com",
                    "created_at": "20190529T00:00:00Z",
                    "updated_at": "20190529T00:00:00Z"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/provider/{providerId}": {
      "get": {
        "operationId": "getProvider",
        "summary": "Get information about a single provider.",
        "parameters": [
          {
            "in": "path",
            "name": "providerId",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Information about a single provider.",
            "content": {
              "application/json": {
                "schema": {
                  "required": [
                    "id",
                    "endpoint_url"
                  ],
                  "properties": {
                    "endpoint_url": {
                      "type": "string"
                    },
                    "id": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string",
                      "format": "date-time"
                    },
                    "updated_at": {
                      "type": "string",
                      "format": "date-time"
                    }
                  },
                  "example": {
                    "id": "f5826b8e-f2aa-4222-9d95-7ed9d05d3f28",
                    "endpoint_url": "http://provider0.example.com",
                    "created_at": "20190529T00:00:00Z",
                    "updated_at": "20190529T00:00:00Z"
                  }
                }
              }
            }
          },
          "default": {
            "description": "Error condition",
            "content": {
              "application/json": {
                "schema": {
                  "required": [
                    "status",
                    "message"
                  ],
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "status": "error",
                  "message": "Provider does not exist."
                }
              }
            }
          }
        }
      },
      "put": {
        "operationId": "updateProvider",
        "summary": "Update provider information",
        "parameters": [
          {
            "in": "path",
            "name": "providerId",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "requestBody": {
          "description": "Updates for this provider",
          "content": {
            "application/json": {
              "schema": {
                "required": [
                  "id",
                  "endpoint_url"
                ],
                "properties": {
                  "endpoint_url": {
                    "type": "string"
                  },
                  "id": {
                    "type": "string"
                  },
                  "created_at": {
                    "type": "string",
                    "format": "date-time"
                  },
                  "updated_at": {
                    "type": "string",
                    "format": "date-time"
                  }
                },
                "example": {
                  "id": "f5826b8e-f2aa-4222-9d95-7ed9d05d3f28",
                  "endpoint_url": "http://provider0.example.com",
                  "created_at": "20190529T00:00:00Z",
                  "updated_at": "20190529T00:00:00Z"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Provider was updated successfully.",
            "content": {
              "application/json": {
                "schema": {
                  "required": [
                    "id",
                    "endpoint_url"
                  ],
                  "properties": {
                    "endpoint_url": {
                      "type": "string"
                    },
                    "id": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string",
                      "format": "date-time"
                    },
                    "updated_at": {
                      "type": "string",
                      "format": "date-time"
                    }
                  },
                  "example": {
                    "id": "f5826b8e-f2aa-4222-9d95-7ed9d05d3f28",
                    "endpoint_url": "http://provider0.example.com",
                    "created_at": "20190529T00:00:00Z",
                    "updated_at": "20190529T00:00:00Z"
                  }
                }
              }
            }
          },
          "default": {
            "description": "Error condition",
            "content": {
              "application/json": {
                "schema": {
                  "required": [
                    "status",
                    "message"
                  ],
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "status": "error",
                  "message": "Provider does not exist."
                }
              }
            }
          }
        }
      },
      "delete": {
        "operationId": "deleteProvider",
        "summary": "Remove a provider from the Marketplace",
        "parameters": [
          {
            "in": "path",
            "name": "providerId",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Provider deleted successfully."
          },
          "default": {
            "description": "Error condition",
            "content": {
              "application/json": {
                "schema": {
                  "required": [
                    "status",
                    "message"
                  ],
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "status": "error",
                  "message": "Provider does not exist."
                }
              }
            }
          }
        }
      }
    },
    "/offer": {
      "get": {
        "operationId": "listOffers",
        "summary": "List currently active offers.",
        "responses": {
          "200": {
            "description": "List of offers",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "properties": {
                      "id": {
                        "description": "UUID of this offer",
                        "type": "string",
                        "format": "uuid"
                      },
                      "project_id": {
                        "description": "UUID of project making this offer",
                        "type": "string",
                        "format": "uuid"
                      },
                      "type": {
                        "description": "what sort of resource does this offer describe?",
                        "type": "string",
                        "enum": [
                          "ironic_node",
                          "dummy_node"
                        ]
                      },
                      "start_date": {
                        "type": "string",
                        "format": "date-time",
                        "example": "20190522T00:00:00Z"
                      },
                      "end_date": {
                        "type": "string",
                        "format": "date-time",
                        "example": "20190527T00:00:00Z"
                      },
                      "status": {
                        "type": "string",
                        "enum": [
                          "open",
                          "claimed",
                          "closed",
                          "deleted"
                        ]
                      },
                      "server": {
                        "properties": {
                          "id": {
                            "type": "string",
                            "format": "uuid",
                            "example": "b5597e97-a43e-4f47-bcb9-70b65cbb23dd"
                          },
                          "project_id": {
                            "description": "UUID of project that owns this server",
                            "type": "string",
                            "format": "uuid"
                          },
                          "properties": {
                            "type": "object",
                            "description": "Free-form metadata attributes that describe this server.",
                            "additionalProperties": true,
                            "example": {
                              "memory_mb": 16384,
                              "cpu_model": "Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz",
                              "cpu_arch": "x86_64",
                              "cpu_physical_count": 1,
                              "cpu_core_count": 8,
                              "cpu_speed_ghz": 3.9,
                              "disks": [
                                {
                                  "size_gb": 500,
                                  "model": "YOYODYNE 1234"
                                },
                                {
                                  "size_gb": 500,
                                  "model": "Serius Cybernetics 4242"
                                }
                              ]
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "operationId": "createOffer",
        "summary": "Create a new offer",
        "requestBody": {
          "description": "Offer details",
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "id": {
                    "description": "UUID of this offer",
                    "type": "string",
                    "format": "uuid"
                  },
                  "project_id": {
                    "description": "UUID of project making this offer",
                    "type": "string",
                    "format": "uuid"
                  },
                  "type": {
                    "description": "what sort of resource does this offer describe?",
                    "type": "string",
                    "enum": [
                      "ironic_node",
                      "dummy_node"
                    ]
                  },
                  "start_date": {
                    "type": "string",
                    "format": "date-time",
                    "example": "20190522T00:00:00Z"
                  },
                  "end_date": {
                    "type": "string",
                    "format": "date-time",
                    "example": "20190527T00:00:00Z"
                  },
                  "status": {
                    "type": "string",
                    "enum": [
                      "open",
                      "claimed",
                      "closed",
                      "deleted"
                    ]
                  },
                  "server": {
                    "properties": {
                      "id": {
                        "type": "string",
                        "format": "uuid",
                        "example": "b5597e97-a43e-4f47-bcb9-70b65cbb23dd"
                      },
                      "project_id": {
                        "description": "UUID of project that owns this server",
                        "type": "string",
                        "format": "uuid"
                      },
                      "properties": {
                        "type": "object",
                        "description": "Free-form metadata attributes that describe this server.",
                        "additionalProperties": true,
                        "example": {
                          "memory_mb": 16384,
                          "cpu_model": "Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz",
                          "cpu_arch": "x86_64",
                          "cpu_physical_count": 1,
                          "cpu_core_count": 8,
                          "cpu_speed_ghz": 3.9,
                          "disks": [
                            {
                              "size_gb": 500,
                              "model": "YOYODYNE 1234"
                            },
                            {
                              "size_gb": 500,
                              "model": "Serius Cybernetics 4242"
                            }
                          ]
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "offer created successfully",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "id": {
                      "description": "UUID of this offer",
                      "type": "string",
                      "format": "uuid"
                    },
                    "project_id": {
                      "description": "UUID of project making this offer",
                      "type": "string",
                      "format": "uuid"
                    },
                    "type": {
                      "description": "what sort of resource does this offer describe?",
                      "type": "string",
                      "enum": [
                        "ironic_node",
                        "dummy_node"
                      ]
                    },
                    "start_date": {
                      "type": "string",
                      "format": "date-time",
                      "example": "20190522T00:00:00Z"
                    },
                    "end_date": {
                      "type": "string",
                      "format": "date-time",
                      "example": "20190527T00:00:00Z"
                    },
                    "status": {
                      "type": "string",
                      "enum": [
                        "open",
                        "claimed",
                        "closed",
                        "deleted"
                      ]
                    },
                    "server": {
                      "properties": {
                        "id": {
                          "type": "string",
                          "format": "uuid",
                          "example": "b5597e97-a43e-4f47-bcb9-70b65cbb23dd"
                        },
                        "project_id": {
                          "description": "UUID of project that owns this server",
                          "type": "string",
                          "format": "uuid"
                        },
                        "properties": {
                          "type": "object",
                          "description": "Free-form metadata attributes that describe this server.",
                          "additionalProperties": true,
                          "example": {
                            "memory_mb": 16384,
                            "cpu_model": "Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz",
                            "cpu_arch": "x86_64",
                            "cpu_physical_count": 1,
                            "cpu_core_count": 8,
                            "cpu_speed_ghz": 3.9,
                            "disks": [
                              {
                                "size_gb": 500,
                                "model": "YOYODYNE 1234"
                              },
                              {
                                "size_gb": 500,
                                "model": "Serius Cybernetics 4242"
                              }
                            ]
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/offer/{offerId}": {
      "get": {
        "operationId": "getOffer",
        "summary": "Get information about a single Offer",
        "parameters": [
          {
            "in": "path",
            "name": "offerId",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Offer detail",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "id": {
                      "description": "UUID of this offer",
                      "type": "string",
                      "format": "uuid"
                    },
                    "project_id": {
                      "description": "UUID of project making this offer",
                      "type": "string",
                      "format": "uuid"
                    },
                    "type": {
                      "description": "what sort of resource does this offer describe?",
                      "type": "string",
                      "enum": [
                        "ironic_node",
                        "dummy_node"
                      ]
                    },
                    "start_date": {
                      "type": "string",
                      "format": "date-time",
                      "example": "20190522T00:00:00Z"
                    },
                    "end_date": {
                      "type": "string",
                      "format": "date-time",
                      "example": "20190527T00:00:00Z"
                    },
                    "status": {
                      "type": "string",
                      "enum": [
                        "open",
                        "claimed",
                        "closed",
                        "deleted"
                      ]
                    },
                    "server": {
                      "properties": {
                        "id": {
                          "type": "string",
                          "format": "uuid",
                          "example": "b5597e97-a43e-4f47-bcb9-70b65cbb23dd"
                        },
                        "project_id": {
                          "description": "UUID of project that owns this server",
                          "type": "string",
                          "format": "uuid"
                        },
                        "properties": {
                          "type": "object",
                          "description": "Free-form metadata attributes that describe this server.",
                          "additionalProperties": true,
                          "example": {
                            "memory_mb": 16384,
                            "cpu_model": "Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz",
                            "cpu_arch": "x86_64",
                            "cpu_physical_count": 1,
                            "cpu_core_count": 8,
                            "cpu_speed_ghz": 3.9,
                            "disks": [
                              {
                                "size_gb": 500,
                                "model": "YOYODYNE 1234"
                              },
                              {
                                "size_gb": 500,
                                "model": "Serius Cybernetics 4242"
                              }
                            ]
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "default": {
            "description": "Error condition",
            "content": {
              "application/json": {
                "schema": {
                  "required": [
                    "status",
                    "message"
                  ],
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "status": "error",
                  "message": "Offer does not exist."
                }
              }
            }
          }
        }
      }
    },
    "/bid": {
      "get": {
        "operationId": "listBids",
        "summary": "Get a list of bids",
        "responses": {
          "200": {
            "description": "A list of bids",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "properties": {
                      "id": {
                        "description": "UUID of this bid",
                        "type": "string",
                        "format": "uuid",
                        "example": "e56afd9e-007a-4a87-a722-6f38f6c204e6"
                      },
                      "project_id": {
                        "description": "UUID of project requesting these resources",
                        "type": "string",
                        "example": "ec9a3f72-af40-44d9-a04c-71c7db7e1ad3"
                      },
                      "start_time": {
                        "description": "Request for resources starting at this time",
                        "type": "string",
                        "format": "date-time",
                        "example": "20190524T00:00:00Z"
                      },
                      "end_time": {
                        "description": "Request for resources ending at this time",
                        "type": "string",
                        "format": "date-time",
                        "example": "20190523T00:00:00Z"
                      },
                      "requirements": {
                        "type": "array",
                        "items": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          },
                          "example": [
                            "memory_mb",
                            ">=",
                            "16192"
                          ]
                        },
                        "example": [
                          [
                            "memory_mb",
                            ">=",
                            "16192"
                          ],
                          [
                            "cost",
                            "<",
                            "0.50"
                          ]
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "operationId": "createBid",
        "summary": "Create a new bid",
        "requestBody": {
          "description": "Bid details",
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "id": {
                    "description": "UUID of this bid",
                    "type": "string",
                    "format": "uuid",
                    "example": "e56afd9e-007a-4a87-a722-6f38f6c204e6"
                  },
                  "project_id": {
                    "description": "UUID of project requesting these resources",
                    "type": "string",
                    "example": "ec9a3f72-af40-44d9-a04c-71c7db7e1ad3"
                  },
                  "start_time": {
                    "description": "Request for resources starting at this time",
                    "type": "string",
                    "format": "date-time",
                    "example": "20190524T00:00:00Z"
                  },
                  "end_time": {
                    "description": "Request for resources ending at this time",
                    "type": "string",
                    "format": "date-time",
                    "example": "20190523T00:00:00Z"
                  },
                  "requirements": {
                    "type": "array",
                    "items": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      },
                      "example": [
                        "memory_mb",
                        ">=",
                        "16192"
                      ]
                    },
                    "example": [
                      [
                        "memory_mb",
                        ">=",
                        "16192"
                      ],
                      [
                        "cost",
                        "<",
                        "0.50"
                      ]
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Bid that was created",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "id": {
                      "description": "UUID of this bid",
                      "type": "string",
                      "format": "uuid",
                      "example": "e56afd9e-007a-4a87-a722-6f38f6c204e6"
                    },
                    "project_id": {
                      "description": "UUID of project requesting these resources",
                      "type": "string",
                      "example": "ec9a3f72-af40-44d9-a04c-71c7db7e1ad3"
                    },
                    "start_time": {
                      "description": "Request for resources starting at this time",
                      "type": "string",
                      "format": "date-time",
                      "example": "20190524T00:00:00Z"
                    },
                    "end_time": {
                      "description": "Request for resources ending at this time",
                      "type": "string",
                      "format": "date-time",
                      "example": "20190523T00:00:00Z"
                    },
                    "requirements": {
                      "type": "array",
                      "items": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        },
                        "example": [
                          "memory_mb",
                          ">=",
                          "16192"
                        ]
                      },
                      "example": [
                        [
                          "memory_mb",
                          ">=",
                          "16192"
                        ],
                        [
                          "cost",
                          "<",
                          "0.50"
                        ]
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/bid/{bidId}": {
      "get": {
        "operationId": "getBid",
        "summary": "Get information about a specific bid",
        "parameters": [
          {
            "in": "path",
            "name": "bidId",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Bid detail",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "id": {
                      "description": "UUID of this bid",
                      "type": "string",
                      "format": "uuid",
                      "example": "e56afd9e-007a-4a87-a722-6f38f6c204e6"
                    },
                    "project_id": {
                      "description": "UUID of project requesting these resources",
                      "type": "string",
                      "example": "ec9a3f72-af40-44d9-a04c-71c7db7e1ad3"
                    },
                    "start_time": {
                      "description": "Request for resources starting at this time",
                      "type": "string",
                      "format": "date-time",
                      "example": "20190524T00:00:00Z"
                    },
                    "end_time": {
                      "description": "Request for resources ending at this time",
                      "type": "string",
                      "format": "date-time",
                      "example": "20190523T00:00:00Z"
                    },
                    "requirements": {
                      "type": "array",
                      "items": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        },
                        "example": [
                          "memory_mb",
                          ">=",
                          "16192"
                        ]
                      },
                      "example": [
                        [
                          "memory_mb",
                          ">=",
                          "16192"
                        ],
                        [
                          "cost",
                          "<",
                          "0.50"
                        ]
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/contract": {
      "get": {
        "operationId": "listContracts",
        "summary": "Get a list of contracts",
        "responses": {
          "200": {
            "description": "A list of contracts",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "properties": {
                      "id": {
                        "description": "UUID of this contract",
                        "type": "string",
                        "format": "uuid",
                        "example": "0e6c010a-d1e8-4da0-bc1d-88d457b04516"
                      },
                      "bid_id": {
                        "description": "UUID of bid associated with this contract",
                        "type": "string",
                        "format": "uuid",
                        "example": "7c2704b3-78b0-4443-b5e7-d05722f6d0c1"
                      },
                      "offer_id": {
                        "description": "UUID of offer associated with this contract",
                        "type": "string",
                        "format": "uuid",
                        "example": "50582bfa-3de5-4eac-a627-f18b5f8a77fe"
                      },
                      "start_date": {
                        "type": "string",
                        "format": "date-time",
                        "example": "20190522T00:00:00Z"
                      },
                      "end_date": {
                        "type": "string",
                        "format": "date-time",
                        "example": "20190527T00:00:00Z"
                      },
                      "status": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Error": {
        "required": [
          "status",
          "message"
        ],
        "properties": {
          "status": {
            "type": "string"
          },
          "message": {
            "type": "string"
          }
        }
      },
      "Provider": {
        "required": [
          "id",
          "endpoint_url"
        ],
        "properties": {
          "endpoint_url": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        },
        "example": {
          "id": "f5826b8e-f2aa-4222-9d95-7ed9d05d3f28",
          "endpoint_url": "http://provider0.example.com",
          "created_at": "20190529T00:00:00Z",
          "updated_at": "20190529T00:00:00Z"
        }
      },
      "ListOfProviders": {
        "type": "array",
        "items": {
          "required": [
            "id",
            "endpoint_url"
          ],
          "properties": {
            "endpoint_url": {
              "type": "string"
            },
            "id": {
              "type": "string"
            },
            "created_at": {
              "type": "string",
              "format": "date-time"
            },
            "updated_at": {
              "type": "string",
              "format": "date-time"
            }
          },
          "example": {
            "id": "f5826b8e-f2aa-4222-9d95-7ed9d05d3f28",
            "endpoint_url": "http://provider0.example.com",
            "created_at": "20190529T00:00:00Z",
            "updated_at": "20190529T00:00:00Z"
          }
        }
      },
      "Offer": {
        "properties": {
          "id": {
            "description": "UUID of this offer",
            "type": "string",
            "format": "uuid"
          },
          "project_id": {
            "description": "UUID of project making this offer",
            "type": "string",
            "format": "uuid"
          },
          "type": {
            "description": "what sort of resource does this offer describe?",
            "type": "string",
            "enum": [
              "ironic_node",
              "dummy_node"
            ]
          },
          "start_date": {
            "type": "string",
            "format": "date-time",
            "example": "20190522T00:00:00Z"
          },
          "end_date": {
            "type": "string",
            "format": "date-time",
            "example": "20190527T00:00:00Z"
          },
          "status": {
            "type": "string",
            "enum": [
              "open",
              "claimed",
              "closed",
              "deleted"
            ]
          },
          "server": {
            "properties": {
              "id": {
                "type": "string",
                "format": "uuid",
                "example": "b5597e97-a43e-4f47-bcb9-70b65cbb23dd"
              },
              "project_id": {
                "description": "UUID of project that owns this server",
                "type": "string",
                "format": "uuid"
              },
              "properties": {
                "type": "object",
                "description": "Free-form metadata attributes that describe this server.",
                "additionalProperties": true,
                "example": {
                  "memory_mb": 16384,
                  "cpu_model": "Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz",
                  "cpu_arch": "x86_64",
                  "cpu_physical_count": 1,
                  "cpu_core_count": 8,
                  "cpu_speed_ghz": 3.9,
                  "disks": [
                    {
                      "size_gb": 500,
                      "model": "YOYODYNE 1234"
                    },
                    {
                      "size_gb": 500,
                      "model": "Serius Cybernetics 4242"
                    }
                  ]
                }
              }
            }
          }
        }
      },
      "ListOfOffers": {
        "type": "array",
        "items": {
          "properties": {
            "id": {
              "description": "UUID of this offer",
              "type": "string",
              "format": "uuid"
            },
            "project_id": {
              "description": "UUID of project making this offer",
              "type": "string",
              "format": "uuid"
            },
            "type": {
              "description": "what sort of resource does this offer describe?",
              "type": "string",
              "enum": [
                "ironic_node",
                "dummy_node"
              ]
            },
            "start_date": {
              "type": "string",
              "format": "date-time",
              "example": "20190522T00:00:00Z"
            },
            "end_date": {
              "type": "string",
              "format": "date-time",
              "example": "20190527T00:00:00Z"
            },
            "status": {
              "type": "string",
              "enum": [
                "open",
                "claimed",
                "closed",
                "deleted"
              ]
            },
            "server": {
              "properties": {
                "id": {
                  "type": "string",
                  "format": "uuid",
                  "example": "b5597e97-a43e-4f47-bcb9-70b65cbb23dd"
                },
                "project_id": {
                  "description": "UUID of project that owns this server",
                  "type": "string",
                  "format": "uuid"
                },
                "properties": {
                  "type": "object",
                  "description": "Free-form metadata attributes that describe this server.",
                  "additionalProperties": true,
                  "example": {
                    "memory_mb": 16384,
                    "cpu_model": "Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz",
                    "cpu_arch": "x86_64",
                    "cpu_physical_count": 1,
                    "cpu_core_count": 8,
                    "cpu_speed_ghz": 3.9,
                    "disks": [
                      {
                        "size_gb": 500,
                        "model": "YOYODYNE 1234"
                      },
                      {
                        "size_gb": 500,
                        "model": "Serius Cybernetics 4242"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "Bid": {
        "properties": {
          "id": {
            "description": "UUID of this bid",
            "type": "string",
            "format": "uuid",
            "example": "e56afd9e-007a-4a87-a722-6f38f6c204e6"
          },
          "project_id": {
            "description": "UUID of project requesting these resources",
            "type": "string",
            "example": "ec9a3f72-af40-44d9-a04c-71c7db7e1ad3"
          },
          "start_time": {
            "description": "Request for resources starting at this time",
            "type": "string",
            "format": "date-time",
            "example": "20190524T00:00:00Z"
          },
          "end_time": {
            "description": "Request for resources ending at this time",
            "type": "string",
            "format": "date-time",
            "example": "20190523T00:00:00Z"
          },
          "requirements": {
            "type": "array",
            "items": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "example": [
                "memory_mb",
                ">=",
                "16192"
              ]
            },
            "example": [
              [
                "memory_mb",
                ">=",
                "16192"
              ],
              [
                "cost",
                "<",
                "0.50"
              ]
            ]
          }
        }
      },
      "ListOfBids": {
        "type": "array",
        "items": {
          "properties": {
            "id": {
              "description": "UUID of this bid",
              "type": "string",
              "format": "uuid",
              "example": "e56afd9e-007a-4a87-a722-6f38f6c204e6"
            },
            "project_id": {
              "description": "UUID of project requesting these resources",
              "type": "string",
              "example": "ec9a3f72-af40-44d9-a04c-71c7db7e1ad3"
            },
            "start_time": {
              "description": "Request for resources starting at this time",
              "type": "string",
              "format": "date-time",
              "example": "20190524T00:00:00Z"
            },
            "end_time": {
              "description": "Request for resources ending at this time",
              "type": "string",
              "format": "date-time",
              "example": "20190523T00:00:00Z"
            },
            "requirements": {
              "type": "array",
              "items": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "example": [
                  "memory_mb",
                  ">=",
                  "16192"
                ]
              },
              "example": [
                [
                  "memory_mb",
                  ">=",
                  "16192"
                ],
                [
                  "cost",
                  "<",
                  "0.50"
                ]
              ]
            }
          }
        }
      },
      "Contract": {
        "properties": {
          "id": {
            "description": "UUID of this contract",
            "type": "string",
            "format": "uuid",
            "example": "0e6c010a-d1e8-4da0-bc1d-88d457b04516"
          },
          "bid_id": {
            "description": "UUID of bid associated with this contract",
            "type": "string",
            "format": "uuid",
            "example": "7c2704b3-78b0-4443-b5e7-d05722f6d0c1"
          },
          "offer_id": {
            "description": "UUID of offer associated with this contract",
            "type": "string",
            "format": "uuid",
            "example": "50582bfa-3de5-4eac-a627-f18b5f8a77fe"
          },
          "start_date": {
            "type": "string",
            "format": "date-time",
            "example": "20190522T00:00:00Z"
          },
          "end_date": {
            "type": "string",
            "format": "date-time",
            "example": "20190527T00:00:00Z"
          },
          "status": {
            "type": "string"
          }
        }
      },
      "ListOfContracts": {
        "type": "array",
        "items": {
          "properties": {
            "id": {
              "description": "UUID of this contract",
              "type": "string",
              "format": "uuid",
              "example": "0e6c010a-d1e8-4da0-bc1d-88d457b04516"
            },
            "bid_id": {
              "description": "UUID of bid associated with this contract",
              "type": "string",
              "format": "uuid",
              "example": "7c2704b3-78b0-4443-b5e7-d05722f6d0c1"
            },
            "offer_id": {
              "description": "UUID of offer associated with this contract",
              "type": "string",
              "format": "uuid",
              "example": "50582bfa-3de5-4eac-a627-f18b5f8a77fe"
            },
            "start_date": {
              "type": "string",
              "format": "date-time",
              "example": "20190522T00:00:00Z"
            },
            "end_date": {
              "type": "string",
              "format": "date-time",
              "example": "20190527T00:00:00Z"
            },
            "status": {
              "type": "string"
            }
          }
        }
      }
    },
    "securitySchemes": {
      "KeystoneAuth": {
        "description": "Openstack Keystone authentication. See the [api reference][1]\nfor details.\n\n[1]: https://developer.openstack.org/api-ref/identity/v3/",
        "type": "apiKey",
        "in": "header",
        "name": "X-Auth-Token"
      }
    }
  }
}